language: node_js
cache:
  directories:
    - node_modules
node_js:
  - '10'
  - '12'
  - '14'
  - '16'

script: 'npm install && npm run ci'
after_success: '<coverage/lcov.info ./node_modules/coveralls/bin/coveralls.js'

